
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 09 23:11:37 PDT 2019
//----------------------------------------------------

package Example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVI = 8;
  public static final int MINUS = 5;
  public static final int INTEGER = 15;
  public static final int POW = 9;
  public static final int TAN = 13;
  public static final int SIN = 11;
  public static final int SEMI = 2;
  public static final int COS = 12;
  public static final int REM = 10;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
  public static final int FLOAT = 14;
}

